name: Deploy Infrastructure

on:
  # Manual-only by default (no auto-deploys on push)
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Skip if the deploy role secret is not configured
    if: ${{ secrets.AWS_DEPLOY_ROLE_ARN != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: infrastructure/package-lock.json

      - name: Install deps
        working-directory: infrastructure
        run: npm ci

      - name: Build
        working-directory: infrastructure
        run: npm run build

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Bootstrap (first-time safe)
        working-directory: infrastructure
        run: npx cdk bootstrap

      - name: Deploy stacks
        working-directory: infrastructure
        run: npx cdk deploy NetworkStack DatabaseStack AuthStack MessagingStack ApiStack MonitoringStack --require-approval never
